# This file was generated by GoReleaser. DO NOT EDIT.
cask "uncluster" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "c888faea74975436be9647546cf54f603c5633d341827a3156ac03bdaa51e1b8"
      url "https://github.com/Derek-X-Wang/uncluster/releases/download/v#{version}/uncluster_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "17e7b96a018c540cc489181949bb6779a97406526de6258b714ae4d29c857e9c"
      url "https://github.com/Derek-X-Wang/uncluster/releases/download/v#{version}/uncluster_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6f7b11517cbf758c7468b8e4493799fb16e74417f1e4b6044d32a0186d69a058"
      url "https://github.com/Derek-X-Wang/uncluster/releases/download/v#{version}/uncluster_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "971f9d24faaa395a751f16fd4e2fa30394e0e26e4eacdbf9a6afbcc9a72d5b3d"
      url "https://github.com/Derek-X-Wang/uncluster/releases/download/v#{version}/uncluster_#{version}_linux_arm64.tar.gz"
    end
  end

  name "uncluster"
  desc "OpenSSH certificate-authority gatekeeper for personal machines"
  homepage "https://github.com/Derek-X-Wang/uncluster"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "uncluster"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/uncluster"]
    end
  end

  # No zap stanza required

end
